### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Epi1278** [Luxocracy/TidyPlatesContinued#11]
Hello! I couldn't find any other way to request this feature, but adding the option to show Threat Percentage on Enemy Status Text would be something I'd really love to see! It was possible with Tidy Plates: Threat, but the theme hasn't been updated for BFA.
Thank you!

**Comment by Luxocracy** [comment]
So I created a quick widget for this, but since I'm not sure what it used to look like with Tidy Plates: Threat, it is currently just a plain text box with your current threat percentage.
Here's a quick preview of it
![Threat Preview](https://i.imgur.com/YdO9Rlq.jpg)

**Comment by Epi1278** [comment]
That looks perfect! Exactly what I was looking for :D

**Comment by vodrinker** [comment]
Hello! I was using old tidy plates for so long. Only thing that i miss when using TP continued is health percentage on EVERY mob around me. I only see status text on target or mouseover. It would be very nice if you change it asap:)

**Comment by Epi1278** [comment]
Does the feature only currently work with a certain theme? I can't seem to get it appearing with the "Grey" theme.
![no threat percentage](https://user-images.githubusercontent.com/28123791/44571015-e9a1f700-a7c2-11e8-8fb3-1233fadfa854.png)

**Comment by Luxocracy** [comment]
This is now included in the latest release which can be found [here](https://luxocracy.github.io/TidyPlatesContinued/) or [here](https://github.com/Luxocracy/TidyPlatesContinued/releases).
