### ISSUE TITLE
Hi luxo 

### ISSUE THREAD

**Issue by Mezq** [Luxocracy/TidyPlatesContinued#16]
Can u fix the combo points bar i just cant stand the ones u have right now cuz they dont look like the real ones from tidyplates here is a screenshot on the real ones https://imgur.com/a/TrrKFK8 hopefuly u can do that would make my day.

**Comment by Luxocracy** [comment]
They do look like this.

In options under "Other Widgets" there is an option called "Personal Resource Style". Change this to TidyPlatesTraditional and it will look like the screenshot no matter which class you play.

**Comment by Luxocracy** [comment]
You'll have to explain/show me exactly what you mean by them not looking the same. Because the traditional style is literally the file used in the original Tidyplates.
And my combo points look like the image you posted. So I am really at a loss here when you say they are different.

**Comment by Mezq** [comment]
Exactly what you edited if u can fix that it would be great, i am still using a super old version of tidyplates cuz of that and it sucks.

**Comment by Luxocracy** [comment]
I've went ahead and did this already so it is already be part of the latest release. I only altered the Traditional styling to include the outline however, I hope this is fine.

**Comment by Mezq** [comment]
All right looks good thank you ! one other thing i dont know if theres a options but to make the combo points look smaller ?

**Comment by Luxocracy** [comment]
No, there is currently no way of resizing the combo points. And it's not something that is a quick fix to add, at least not from the look of things. So unless I decide to take the time to make everything movable it probably won't happen for a while.
