### ISSUE TITLE
double timers

### ISSUE THREAD

**Issue by aden928** [Luxocracy/TidyPlatesContinued#18]
After yesterday's update, I found 2 timers running on debuffs. I am sure it startd yesterday. I belive one is from omnicc and the other is from the tidy plates continued iteself. I tried to disable omnicc, and it shows only 1 timer. I want to keep using both omnicc and tidyplatescontinued, is there any solutions to it?
![wowscrnshot_091718_011031](https://user-images.githubusercontent.com/43330481/45638238-9d24a100-ba7a-11e8-98b5-6bab290622b4.jpg)

**Comment by Luxocracy** [comment]
Yes, the latest release has a fix specifically for this issue.
