### ISSUE TITLE
dispellable buffs highlight

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/TidyPlatesContinued#20]
I love the possibility to see dispellable buffs on nameplates, I'm using a WA for this which glows when it is actually dispellable by that character but also like that TP shows the others too. But sometimes it gets a bit crowded when both are shown, especially there are multiple dispellable buffs on multiple enemies so I'd like to turn this WA off. Would it be possible for TP to show an additional effect (preferably glow) on those I can actually dispel?

**Comment by Luxocracy** [comment]
Not sure what you mean, if the buff aura is displayed it is dispellable. It doesn't show auras that can't be removed.

**Comment by hollo6** [comment]
I mean it shows Magic and Enrage regardless of the spec I'm playing. I'd like to distinctly see the buffs I can actually remove, like Enrages highlighted on a Druid and Magics on a Priest.

**Comment by Luxocracy** [comment]
Profiles are character specific so there really shouldn't be a need for the addon to choose to hide dispellable buffs if you have it checked just because you can't remove them.

**Comment by hollo6** [comment]
I don't want it to hide them if I can't dispel them, I just want the ones I can dispel to be highlighted.

**Comment by Luxocracy** [comment]
Ok I kinda see what you are getting at. But they can already be distinguished by setting different border colors. Are you saying that isn't enough for you?

**Comment by hollo6** [comment]
Yes I guess I'm tring to say that. But it's not just that, more like that I'm playing multiple characters regularly and in the heat of a difficult fight I don't always realize fast enough which one I'm on to decide to attempt a dispel accordingly.

**Comment by Luxocracy** [comment]
Here's what I'm thinking, I could probably add an option for setting which type of highlighting you want for purgeable/enrage buffs. So you would choose between glow and border color for purgeable and enrage effects separately. But then it would be up to you to set it up properly on each character.

I want to avoid adding class specific stuff when possible due to the game always changing, and I could just imagine hunters being annoying since they require a specific pet to dispell. Either way it would be an option you would have to check. And I feel like the first option has more use cases.

**Comment by hollo6** [comment]
I understand your reasoning perfectly and couldn't agree more. The option to choose between glow and border color would be totally enough since if the setting is character specific, we're capable to set this up differently on different characters.

**Comment by Malhira** [comment]
debuffs are not shown any more above the name plates.  The function is turned on in the options but doesn't work :(   In any case thank you so very much for working at this addon

**Comment by Luxocracy** [comment]
@Malhira Did the debuffs show up in previous version? Because I have not come across this issue myself. A common issue however is that the profile selected for your spec is incorrect, so you are editing a profile not being used.

**Comment by Malhira** [comment]
Thanks for the reply! Yes, they were shown above the name plate (till today update, so yesterday they existed) A correct profile is chosen.  https://prnt.sc/kw7w8e my profile. https://prnt.sc/kw7wmi profile 2 example https://prnt.sc/kw7wxd  nothing above the name plate and I can see the debuff with the help of tell me when only

**Comment by Luxocracy** [comment]
I believe you might have activated the old TidyPlates by mistake, your version reads as 6.19.Alpha1. While this addons version is either 6.21.6 or 6.21.7 depending on if you are using the beta release or not.

**Comment by Malhira** [comment]
omg, it was downloaded automatically today from curse. I'll try to reinstall. Thank you. Sorry, I am dumb xD

**Comment by hollo6** [comment]
Looks just like I imagined, there is one side effect though. Sometimes the dispellables appear above the others, like they were shifted up by a row. This happened in ~40% of the cases earlier and now seems almost 100%.
Looks like this:
![image](https://user-images.githubusercontent.com/365584/45807006-b7e95680-bcc2-11e8-8af2-b65656586044.png)

**Comment by Luxocracy** [comment]
This is intentional behaviour to separate your debuffs from your buffs.
The fact that it wasn't a 100% previously is very surprising to me since I've changed nothing about it since the addition of buffs.

**Comment by hollo6** [comment]
Strange. But since I don't want to see that many debuffs anyway (kinda kills the point, I have set up all my chars to show just the 2-3 most relevant ones), would it be possible to have the dispellables to be in the same row?  This 2 row makes very difficult to see what's what when there is more enemies in a cluster, even at 3 or 3 trash mobs all having some enrage on them.

**Comment by Luxocracy** [comment]
I normally play with Wide icons and for Wide icons I very much prefer the way it is handled now. However I do recognize how weird this looks when using Compact icons. So what I was toying around with was something like this.
![](https://i.imgur.com/1njtXrb.jpg)

Where as long as they fit they would stay on the same row, but if they were to overlap they move up a row. I'm just unsure whether or not I want to be default behavior, a setting, or exclusive to Compact icons. 

Gonna play around with it a bit before making up my mind on that one, but for now I've released a new [beta version](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.7-beta2) with this in it.

**Comment by hollo6** [comment]
Looks all nice now, thanks a lot! Whatever you decide about the setting/default stuff, I'll be happy with the look I get right now.

**Comment by Luxocracy** [comment]
This is now part of the [latest release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.7), I ended up going with a slider for the setting so you can decide how much spacing you want between the buffs & debuffs.
Maxing it will mean buffs always appear on their own row.
