### ISSUE TITLE
Range / Filter

### ISSUE THREAD

**Issue by xleeverx** [Luxocracy/TidyPlatesContinued#22]
Good morning, I have a question.

Can I adjust somewhere, the distance of the displayed bars.

A filter from which meter the bars can no longer be displayed.

In Höusern is the teiwleise really annoying.

Thank you very much.

**Comment by Luxocracy** [comment]
Yes, at the bottom under "Funky Stuff" you can set Nameplate Distance

**Comment by xleeverx** [comment]
Hello,
yes I have tried synonymous but I have no change.

Even after a / reload not.

**Comment by Luxocracy** [comment]
Turns out I had accidentally misspelled something when I attempted to fix an error that was sometimes happening. This should be working in the coming release.

Until then you can run this command in chat.

`/run SetCVar("nameplateMaxDistance", 60)`

Just change the number to what you want.

**Comment by xleeverx** [comment]
thanks very nice, it works

**Comment by Luxocracy** [comment]
This is now fixed in the [latest release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.7)
