### ISSUE TITLE
My nameplate

### ISSUE THREAD

**Issue by Yasinahh** [Luxocracy/TidyPlatesContinued#24]
Hi, Is there a function to Display My name as a Nameplate like the other Players? I only Can Modify Friendly and Enemy nameplates but not my Own nameplate. or i have overlooked this?

**Comment by Luxocracy** [comment]
There is an option to display your own healthbar in the normal interface options.
However, this addon currently does not affect/skin that healthbar due to it causing some rather major issues.

**Comment by Yasinahh** [comment]
Ok

and is there an option to display the player titles in the Players headline?

**Comment by Luxocracy** [comment]
No, not as far as I am aware.

**Comment by Yasinahh** [comment]
ok, thx! :-)
