### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/TidyPlatesContinued#26]
15x [ADDON_ACTION_BLOCKED] 插件 'TidyPlatesContinued' 尝试调用保护功能 'SetNamePlateEnemySize()'。
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetNamePlateEnemySize'
TidyPlatesContinued\TidyPlatesCore.lua:88: in function <TidyPlatesContinued\TidyPlatesCore.lua:83>
TidyPlatesContinued\TidyPlatesCore.lua:108: in function <TidyPlatesContinued\TidyPlatesCore.lua:96>
TidyPlatesContinued\TidyPlatesCore.lua:425: in function <TidyPlatesContinued\TidyPlatesCore.lua:419>
TidyPlatesContinued\TidyPlatesCore.lua:149: in function <TidyPlatesContinued\TidyPlatesCore.lua:128>

Locals:
InCombatSkipped

**Comment by yishuangfrank** [comment]
插件=addon
尝试调用保护功能=Try to call protection function

**Comment by Luxocracy** [comment]
Where you using the [Beta2 release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.8-beta2)?
Because I believe this is something that shouldn't happen in that release.

**Comment by yishuangfrank** [comment]
“Change how often we attempt to set the nameplate size and will not attempt to set it in combat(as they are protected functions that can't be set in combat)”

You have fixed it in beta2.

**Comment by yishuangfrank** [comment]
BTW,you forgot to change the Version to "beata2" in TidyPlatesContinued.toc.
