### ISSUE TITLE
Alvara Elite Icon?

### ISSUE THREAD

**Issue by Varinn24** [Luxocracy/TidyPlatesContinued#27]
Hi,

I would appreciate ANY help with this "Issue".
Since there are several nice themes of the awesome Addon Tidyplates, i'd really like to fully enjoy that Addon. But also I always struggle with choosing between what i like: Alvara Theme, Graphite Theme - or pick Grey or alot of other personally not good looking Themes where i can see an Elite Icon or the Health Percentage. 

My Issue here is now, I want to see an Elite Icon on Alvara Theme. How can I eidt those Themes?

Regards,

Varinn

**Comment by Luxocracy** [comment]
You would have to edit the actual theme file for that to show up.
And adding something like this

_TidyPlatesContinued_Alvara.lua_
```
Alvara.eliteicon = {
	texture = path.."\\EliteIcon",
	width = 14,
	height = 14,
	x = -51,
	y = 17,
	anchor = "CENTER",
	show = true,
}
```

You might also have to add the _EliteIcon.tga_ from another themes media folder to Alvara's media folder

**Comment by ja0b** [comment]
Oo damn you're fast! Here is the PR: https://github.com/Luxocracy/TidyPlatesContinued/pull/28

**Comment by Varinn24** [comment]
Fml you really both are fast - Thank you so far, I will just try it and give you some Information right after.

**Comment by Varinn24** [comment]
It worked, i am very happy with this support! 

Much Regards,

Varinn.

**Comment by Varinn24** [comment]
Another Question: what do I have to add to the lua to activate the estimated Health option?

**Comment by Luxocracy** [comment]
I believe something like this would do it

```
Alvara.customtext = {
	typeface = font,
	width = 90,
	x = -3,
	y = 1.5,
	align = "CENTER",
	shadow = false,
	show = true,
}
```

**Comment by Varinn24** [comment]
Thank you alot.

**Comment by Luxocracy** [comment]
This is now part of the [latest beta release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.8-beta3).

**Comment by Rhess86** [comment]
Glad to see that you havent abandoned the project just because the official is back, its so outdated and missing some neat features you implemented. At least i dont plan to go back to that as long you keep up the amazing work. Thanks.

**Comment by Varinn24** [comment]
It's nice to see how you work for this addon - i've updated the version and now enjoy the optimized themes of Alvara - BUT - the elite Icon on Graphite is not working for me - i see a green square which is quiet ugly. I already tried to import the eliteicon.lua from other themes but they dont work - i still see a green square. Thank you for your work - can you help me out on this one more time?

**Comment by Varinn24** [comment]
It worked with a restart of the game - ty - usually /rl worked for nearly everything, thats why i didnt try to restart tho - sorry, good work!

**Comment by Luxocracy** [comment]
As long as there are no new file added, a simple reload is enough. But if something was added wow needs to be restarted.
