### ISSUE TITLE
feature request: rare indicator

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/TidyPlatesContinued#29]
It would be very beneficial to be able to see if a mob is Rare (especially in IEs), I'm thinking something like the quest indicator, maybe at the same place.
Could you please add this feature?

**Comment by Luxocracy** [comment]
Since in the default UI the Rare icon is just a desaturated/gray version of the Elite icon, I decided to do the same. It was also an incredibly easy solution to this, so this will be included in the next release.

**Comment by hollo6** [comment]
Thank you very much!
