### ISSUE TITLE
Hey hey wink  wink ;)

### ISSUE THREAD

**Issue by AHigi** [Luxocracy/TidyPlatesContinued#3]
https://github.com/AHigi/TidyPlates wanna pool resources?
found the lagg solution btw, check out my last commit

**Comment by Luxocracy** [comment]
Well that's an annoyingly simplistic solution...
And sure we can do that.

**Comment by AHigi** [comment]
Indeed... I was diggin around widgets, I thought they've been the issue... but was barking on the wrong tree all along...  so if you want we can create a combined repo so that we may both do the best we can to keep this project alive

**Comment by Luxocracy** [comment]
Yeah sure, not really sure how we go about doing that though so if you know that would be great.

**Comment by AHigi** [comment]
ikr well you can add me to this repo of yours, i merge my commits into this one, and we just beautify it as we see fit :P

**Comment by WhatsTheIssue** [comment]
Yay we're all best friends.

I tried to use alternative addons when I thought TidyPlates was finally going to be dead, and it just wasn't the same.

**Comment by AHigi** [comment]
I more thing... I contacted the original author of the project to find out if he even wants to continue to work on this project. Or just add us to the contributors on curseforge. If we get no answer, we could just create a forge project too, so ppl could just download it via twitch client.

**Comment by AHigi** [comment]
I know them feelz @WhatsTheIssue, I took this one for granted aswell. I got really dependent on this addon. So it was just obvious if noone came forth to fix it, I could just try (having programming background)

**Comment by ja0b** [comment]
@AHigi good idea, let us know if the authors say something, if not then you guys need to start thinking in another name 😂  _bfa is not a good one for the twitch client.

**Comment by WhatsTheIssue** [comment]
**As long as you credit the original authors**, I'm sure curse would accept TidyPlates2

**Comment by AHigi** [comment]
Indeed, the credits go to the original authors always... I'm personaly not looking for any... I don't know... fame or something. Just let ppl continue to use this addon who love it the way I do :)

**Comment by AHigi** [comment]
TidyPlates Continued ? :)

**Comment by Diablolock** [comment]
GJ you two! A new version on curse would be great!

TYVM guys,

**Comment by AHigi** [comment]
created a project for it on curse, not yet fully working, need your name there @Luxocracy to add you to the project

**Comment by Luxocracy** [comment]
It should be the same there as here.

**Comment by ja0b** [comment]
@AHigi any updates on the authors?

**Comment by AHigi** [comment]
I'm working on publishing the addon on curse, but there's some issue I can't figure out. I did everything right but it get's rejected. I've contacted the curse support, so it's almost done.

**Comment by ja0b** [comment]
Great! Looking forward to seeing it soon on curse and ready to collaborate in the bug fixing part :)
