### ISSUE TITLE
Issues with Chinese characters

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/TidyPlatesContinued#31]
There's this long standing issue with Tidy Plates that Chinese characters are not well supported. 

Features like tug-o-threat and the input frame of color/filter by unit-name would show ?????? instead of correct chinese.

I don't know how to add chinese character set support. Can you shed some light on this issue?

**Comment by Luxocracy** [comment]
I believe this would be down to the actual fonts used not supporting Chinese characters.

So either you could replace the font file used by the theme you are using, or under 'Funky Stuff' there is an option to use blizzards font that shouldn't have this issue.
