### ISSUE TITLE
 6.21.10 issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/TidyPlatesContinued#32]
```
16x ...ceTidyPlatesContinuedHub\functions\Color-颜色.lua:225: Usage: UnitAura("unit", [index][, "filter"])
[C]: in function `UnitAura'
...ceTidyPlatesContinuedHub\functions\Color-颜色.lua:225: in function `SetHealthbarColor'
TidyPlatesContinued\TidyPlatesCore.lua:710: in function <TidyPlatesContinued\TidyPlatesCore.lua:707>
TidyPlatesContinued\TidyPlatesCore.lua:780: in function <TidyPlatesContinued\TidyPlatesCore.lua:761>
TidyPlatesContinued\TidyPlatesCore.lua:333: in function <TidyPlatesContinued\TidyPlatesCore.lua:309>
TidyPlatesContinued\TidyPlatesCore.lua:448: in function <TidyPlatesContinued\TidyPlatesCore.lua:444>
TidyPlatesContinued\TidyPlatesCore.lua:986: in function `?'
TidyPlatesContinued\TidyPlatesCore.lua:934: in function <TidyPlatesContinued\TidyPlatesCore.lua:933>

Locals:
InCombatSkipped
```

**Comment by Luxocracy** [comment]
Are you doing anything in particular to get this to happen?

Because I can't reproduce it on my end.

**Comment by yishuangfrank** [comment]
Maybe I used Spell ID instead of buff‘s name in “Cutom Color Conditions”？

**Comment by yishuangfrank** [comment]
In “Custom Color Conditions”，I changed Spell ID to buff's name. I will test it later.
BTW，Shold there be  a "space" between Color value and Unit Name/Buff Name

**Comment by yishuangfrank** [comment]
> Are you doing anything in particular to get this to happen?
> 
> Because I can't reproduce it on my end.

I used Spell ID instead of buff‘s name in “Custom Color Conditions”.

**Comment by Luxocracy** [comment]
Yes, there needs to be a space between the color and the spełl name.

Currently, spellid isn't supported, mostly because I forgot to include it. I'll add that in as soon as I can.

**Comment by yishuangfrank** [comment]
Wonderful！Thanks！

**Comment by Luxocracy** [comment]
Are you still getting the error in the first post in the 10a version? Or did that fix it?

**Comment by yishuangfrank** [comment]
I palyed for a while, no eeror up to now.
