### ISSUE TITLE
6.21.10b issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/TidyPlatesContinued#33]
Spell ID doesn't work.
![tim 20181107213201](https://user-images.githubusercontent.com/44251440/48134380-b7d60200-e2d4-11e8-9ed4-998c7792bb50.png)
![tim 20181107213117](https://user-images.githubusercontent.com/44251440/48134384-bc021f80-e2d4-11e8-8770-ca97328d46ac.png)

**Comment by Luxocracy** [comment]
Seemingly it doesn't work with buffs due to something I overlooked because I only briefly tested it. I guess I should start being a bit more thorough with testing before uploading...

Anyways, [this](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.10c) should work.

**Comment by yishuangfrank** [comment]
good job！

**Comment by yishuangfrank** [comment]
OK，It works well.
![tim 20181107222813](https://user-images.githubusercontent.com/44251440/48137188-76495500-e2dc-11e8-9c98-759b5a392e50.png)
