### ISSUE TITLE
About Additional Auras

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/TidyPlatesContinued#34]
I updated TPC to v6.21.11.
The icon of Additional Auras became another rolling one.

**Comment by Luxocracy** [comment]
What is happening exactly? I don't quite understand what you mean by this.

**Comment by yishuangfrank** [comment]
Later，I'm in a raid.

**Comment by yishuangfrank** [comment]
1. I'm a mage.I monitored a PVP buff，Spell ID is 198121
![1](https://user-images.githubusercontent.com/44251440/48204064-eb339200-e3a3-11e8-8abd-7aae3ecbc585.png)
![2](https://user-images.githubusercontent.com/44251440/48204185-32218780-e3a4-11e8-9bb0-56d03b8843e5.png)
![3](https://user-images.githubusercontent.com/44251440/48204291-69903400-e3a4-11e8-8a12-a14804e7488a.png)

2. In previous versions，the buff’s icon on the nameplate is like this：
![0](https://user-images.githubusercontent.com/44251440/48204489-e4594f00-e3a4-11e8-90e7-74f97e98ea37.png)

3. But in v6.21.11. This icon is changed to another one，and it is turning.
![00](https://user-images.githubusercontent.com/44251440/48204703-72cdd080-e3a5-11e8-9970-17e0bf8f0ba9.png)

**Comment by yishuangfrank** [comment]
I tested other buffs，they all change to the same icon like this：
![00](https://user-images.githubusercontent.com/44251440/48205577-6b0f2b80-e3a7-11e8-982c-38fd80b28cc0.png)

**Comment by Luxocracy** [comment]
That is extremely weird. And just because it's always best to check, did you restart wow?

Because even though no new files should have been added to make a restart required, it is similar to issues it can produce.

**Comment by yishuangfrank** [comment]
Please close it.
I redownload v6.21.11，and the icon becomes normal.
