### ISSUE TITLE
bossicon(skull) position

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/TidyPlatesContinued#35]
Not a bug, but now that eliteicon is hidden when it's a boss, I find it more visually consistent to make the bossicon positioned where the eliteicon used to be (left end of healthbar). It's easy to modify by changing the x value for every theme.

Just a suggestion.

**Comment by Luxocracy** [comment]
It is something I was considering doing when the change was made and then I guess I just kinda forgot about it.

So this will be fixed for the next release.

**Comment by Luxocracy** [comment]
This is now part of the [latest release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.11a).
