### ISSUE TITLE
class colored friendly nameplates without health bars

### ISSUE THREAD

**Issue by Qwers** [Luxocracy/TidyPlatesContinued#43]
(sorry for my bad english)

I try to config friendly nameplates (i know that we can't change them in raids/instance) and there are some problems. My goal was to only display class colored nickname without health bar (something like this: 
![kui_nameplates](https://user-images.githubusercontent.com/10394723/48574811-6949e880-e910-11e8-87eb-206ae5afa953.jpg) - this is random ss from kui nameplates).

In 7.3 Blizz add an option to hide the friendly nameplate health bar and only show the name: "nameplateShowOnlyNames". Without TidyPlates it looks like that: 
![blizz_nameplates_name_only](https://user-images.githubusercontent.com/10394723/48580497-af5a7880-e91f-11e8-8447-524f6b8c886f.jpg)

This option is not working well with Tidy Plates. When i have enabled friendly nameplates it looks like that (nameplateShowOnlyNames 0):
![tp_nameplates_on](https://user-images.githubusercontent.com/10394723/48584333-bdad9200-e929-11e8-8ec5-c8d6eb379b12.jpg)

TP settings: 
![tp_settings](https://user-images.githubusercontent.com/10394723/48584401-edf53080-e929-11e8-918b-1d9c997d25c9.jpg)

When i disable friendly players health bars in TP it looks like that (it doesnt matter if i have enable or disable nameplateShowOnlyNames - effect is same in both case):
![tp_np_disabled](https://user-images.githubusercontent.com/10394723/48588143-28fd6100-e936-11e8-9d55-4d6e0c552cfb.jpg)

Same settings with target someone:
![tp_np_disabled_target](https://user-images.githubusercontent.com/10394723/48585046-ba1b0a80-e92b-11e8-86c6-3e07e9b62070.jpg)

Additionally with this settings ("nameplateShowOnlyNames 1" and disabled players health bars in TP) i have this lua error:

> Date: 2018-11-16 00:31:29
ID: 2
Error occured in: Global
Count: 1
Message: ...erface\AddOns\TidyPlatesContinued\TidyPlatesCore.lua line 422:
   table index is nil
Debug:
   [C]: ?
   ...erface\AddOns\TidyPlatesContinued\TidyPlatesCore.lua:422:
      ...erface\AddOns\TidyPlatesContinued\TidyPlatesCore.lua:412
   ...erface\AddOns\TidyPlatesContinued\TidyPlatesCore.lua:1078: ?()
   ...erface\AddOns\TidyPlatesContinued\TidyPlatesCore.lua:1038:
      ...erface\AddOns\TidyPlatesContinued\TidyPlatesCore.lua:1037

So there are some problems:
1. Guild names are visible even when i disable it
![guild name](https://user-images.githubusercontent.com/10394723/48588517-b7bead80-e937-11e8-9705-19f69a893af8.jpg)

2. If i target someone the health bar is showing
![tp_np_disabled_target](https://user-images.githubusercontent.com/10394723/48588595-053b1a80-e938-11e8-952e-3d24b501c35e.jpg)

3. Nicknames dont have class colors with "Players health bar" disabled

**Comment by Luxocracy** [comment]
Did not know that blizz had added a CVar for not displaying health bars, I'll look into getting TPC to respect that setting.

But mainly this just seems to be a configuration issue.
The settings you are looking for are under **Headline View (Text-Only)**
**Headline Color** would be their name color
**Headline Subtext** is their guild etc. So you would set that to _None_ in your case.
As for their health bar showing up when you target them, that is due to you having **Force Bars on Targets** enabled.

And the lua error related to another issue which should be fixed in the next release.

**Comment by Qwers** [comment]
Thanks. I will check this.
